- name: Installing Apache
  hosts: all
  become: yes
  tasks:
    - name: Setup Apache - Debian
      apt:
        update_cache: yes
        name: apache2
        state: present
      when: ansible_distribution == 'Debian'

    - name: Setup Apache - RHEL
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'RedHat'